// School data for the U.S. News 2027 Best National Universities top 20
// (22 schools, because three are tied at No. 20).
//
// Figures come from each school's 2025-26 Common Data Set, official
// announcements, and student-newspaper reporting of Class of 2030 results.
// Anything a school has not published is marked `estimated: true` and is a
// published third-party estimate or a figure derived from published counts.

export const RANKING = {
  publisher: 'U.S. News & World Report',
  list: 'Best National Universities',
  edition: '2027',
  released: 'September 2026',
};

export const CYCLE = '2026–27 application cycle (fall 2027 entry)';
export const DATA_AS_OF = 'October 2026';

// Common Data Set section C7 levels.
export const VI = 3; // Very important
export const IM = 2; // Important
export const CO = 1; // Considered
export const NC = 0; // Not considered

// Schools whose C7 "level of applicant's interest" rating was confirmed.
export const INTEREST_REPORTED = new Set([
  'duke', 'dartmouth', 'northwestern', 'rice', 'washu',
  'harvard', 'yale', 'princeton', 'stanford', 'vanderbilt', 'cmu', 'mit',
]);

export const C7_LABELS = { 3: 'Very important', 2: 'Important', 1: 'Considered', 0: 'Not considered' };

export const C7_FACTORS = [
  ['rigor', 'Rigor of secondary school record'],
  ['rank', 'Class rank'],
  ['gpa', 'Academic GPA'],
  ['tests', 'Standardized test scores'],
  ['essay', 'Application essay'],
  ['recs', 'Recommendation(s)'],
  ['interview', 'Interview'],
  ['ecs', 'Extracurricular activities'],
  ['talent', 'Talent / ability'],
  ['character', 'Character / personal qualities'],
  ['firstGen', 'First generation'],
  ['alumni', 'Alumni/ae relation'],
  ['geography', 'Geographical residence'],
  ['volunteer', 'Volunteer work'],
  ['work', 'Work experience'],
  ['interest', "Level of applicant's interest"],
];

// Typical profile of a highly selective private university's C7 grid,
// used where a school's own grid could not be confirmed.
const ELITE_PRIVATE = {
  rigor: VI, rank: CO, gpa: VI, tests: IM, essay: VI, recs: VI, interview: CO,
  ecs: VI, talent: IM, character: VI, firstGen: CO, alumni: CO, geography: CO,
  volunteer: CO, work: CO, interest: NC,
};

const c7 = (overrides) => ({ ...ELITE_PRIVATE, ...overrides });

const UC_C7 = {
  rigor: VI, rank: NC, gpa: VI, tests: NC, essay: VI, recs: NC, interview: NC,
  ecs: IM, talent: IM, character: IM, firstGen: CO, alumni: NC, geography: CO,
  volunteer: CO, work: CO, interest: NC,
};

const GENERAL_SOURCES = {
  usnews: {
    label: 'U.S. News: MIT claims No. 1 spot in 2027 Best Colleges rankings',
    url: 'https://www.usnews.com/info/blogs/press-room/articles/2026-09-22/mit-claims-no-1-spot-in-u-s-news-2027-best-colleges-rankings',
  },
  class2030: {
    label: 'College Essay Advisors: Class of 2030 admissions statistics',
    url: 'https://www.collegeessayadvisors.com/acceptance-rates-and-admissions-statistics-for-top-schools/',
  },
};

export const SCHOOLS = [
  {
    id: 'mit',
    name: 'Massachusetts Institute of Technology',
    short: 'MIT',
    rank: 1,
    city: 'Cambridge, MA',
    admit: { rate: 0.0458, applicants: 28349, admitted: 1299, cls: 2030 },
    early: { plan: 'EA', label: 'Early Action (non-binding, non-restrictive)', binding: false, restrictive: false, rate: 0.0551, applicants: 11883, admitted: 655, cls: 2030 },
    rd: { rate: 0.0391, estimated: true, note: 'Derived: (1,299 − 655) ÷ (28,349 − 11,883)' },
    tests: { policy: 'required', sat: [1520, 1570], act: [34, 35] },
    legacy: 'none',
    interview: 'evaluative',
    athletics: 'D3',
    c7: c7({ rigor: IM, rank: CO, gpa: IM, tests: IM, essay: IM, recs: IM, interview: IM, ecs: IM, talent: IM, character: VI, alumni: NC, interest: NC }),
    c7Verified: 'partial',
    majors: { humanities: 0.8, socsci: 0.85, business: 0.85, arts: 0.8 },
    poolShift: 0,
    facts: [
      'Character and personal qualities is the only factor MIT rates "very important" in its Common Data Set; grades, rigor, tests, essays, recommendations, the interview and activities are all "important".',
      'Uses its own application (not the Common App) with several short-answer essays in place of a single personal statement.',
      'Applicants are admitted to MIT as a whole; no major is declared on the application.',
      'Early Action is non-binding and non-restrictive. The early admit rate (5.5%) is only modestly above regular decision (≈3.9%).',
      'MIT has never given legacy preference.',
      'Optional Maker Portfolio and arts portfolios let you show work that does not fit an activities list.',
    ],
    sources: [
      { label: 'MIT Common Data Set 2025–26', url: 'https://ir.mit.edu/projects/2025-26-common-data-set/' },
      GENERAL_SOURCES.class2030,
    ],
  },
  {
    id: 'princeton',
    name: 'Princeton University',
    short: 'Princeton',
    rank: 2,
    city: 'Princeton, NJ',
    admit: { rate: 0.040, applicants: 46618, admitted: null, cls: 2030 },
    early: { plan: 'SCEA', label: 'Single-Choice Early Action (restrictive)', binding: false, restrictive: true, rate: 0.14, estimated: true, cls: null, note: 'Not published since the Class of 2024 (15.8%); recent history 13–16%.' },
    rd: { rate: 0.031, estimated: true, note: 'Industry estimate (≈3–4%).' },
    tests: { policy: 'optional', sat: [1490, 1560], act: [34, 35], note: 'Test-optional for the last time in 2026–27. SAT or ACT required starting with the 2027–28 cycle (fall 2028 entry).' },
    legacy: 'strong',
    interview: 'informational',
    athletics: 'D1',
    c7: c7({ tests: VI, talent: VI, interest: NC }),
    c7Verified: 'partial',
    majors: {},
    poolShift: 0,
    facts: [
      'Class of 2030 admit rate was 4.0% of 46,618 applicants, the lowest in Princeton history; 76% of admits enrolled.',
      'Rates rigor, GPA, test scores, essay, recommendations, activities, talent and character all "very important".',
      'Requires a graded written paper from a junior- or senior-year class.',
      'Has withheld early-round statistics since 2021.',
      'Reinstating required SAT/ACT scores starting with the 2027–28 cycle after a five-year review found submitters performed better.',
    ],
    sources: [
      { label: 'Daily Princetonian: Class of 2030 acceptance rate 4.0%', url: 'https://www.dailyprincetonian.com/article/2026/09/princeton-news-adpol-admissions-class-of-2030-lowest-ever-acceptance-rate' },
      { label: 'Princeton: Standardized testing policy beginning with 2027–28', url: 'https://admission.princeton.edu/apply/standardized-testing' },
      { label: 'Princeton Common Data Set 2025–26', url: 'https://ir.princeton.edu/document/606' },
    ],
  },
  {
    id: 'harvard',
    name: 'Harvard University',
    short: 'Harvard',
    rank: 3,
    city: 'Cambridge, MA',
    admit: { rate: 0.0418, applicants: 47893, admitted: 2003, cls: 2029, note: 'Class of 2030 figures were withheld; third-party estimates ≈3.7%.' },
    early: { plan: 'REA', label: 'Restrictive Early Action', binding: false, restrictive: true, rate: 0.087, estimated: true, cls: 2028, note: 'Last published: 692 of 7,921 (Class of 2028). Estimates for 2029–30 are 8–9%.' },
    rd: { rate: 0.028, estimated: true, note: 'Estimate for the Class of 2029.' },
    tests: { policy: 'required', sat: [1510, 1580], act: [34, 36] },
    legacy: 'strong',
    interview: 'evaluative',
    athletics: 'D1',
    c7: c7({ tests: VI, interview: VI, talent: VI, interest: NC }),
    c7Verified: 'partial',
    majors: {},
    poolShift: 0,
    facts: [
      'Rates rigor, GPA, tests, essay, recommendations, interview, activities, talent and character all "very important".',
      'Readers score academic, extracurricular, athletic and personal ratings on a 1–6 scale (1 = best). An extracurricular "1" signals unusual, often national-level achievement; a "2" signals state or regional distinction and leadership.',
      'In data released in SFFA v. Harvard, recruited athletes were admitted at 86%, children of faculty at 47%, dean\'s-interest applicants at 42% and legacies at 34%, versus under 5.5% for everyone else.',
      'In the same data, the top academic-index decile was admitted at roughly 13–15%; the bottom decile was almost never admitted.',
      'Has stopped publishing round-by-round admissions statistics.',
    ],
    sources: [
      { label: 'Harvard Common Data Set 2025–26 (collegedata.fyi)', url: 'https://www.collegedata.fyi/schools/harvard/2025-26' },
      { label: 'Arcidiacono, Kinsler & Ransom: Legacy and Athlete Preferences at Harvard', url: 'https://public.econ.duke.edu/~psarcidi/legacyathlete.pdf' },
      { label: 'Oriel Admissions: Harvard early action acceptance rate', url: 'https://orieladmissions.com/harvard-early-action-acceptance-rate/' },
    ],
  },
  {
    id: 'yale',
    name: 'Yale University',
    short: 'Yale',
    rank: 4,
    city: 'New Haven, CT',
    admit: { rate: 0.0424, applicants: 54919, admitted: 2328, cls: 2030 },
    early: { plan: 'SCEA', label: 'Single-Choice Early Action (restrictive)', binding: false, restrictive: true, rate: 0.109, applicants: 7140, admitted: 779, cls: 2030 },
    rd: { rate: 0.029, estimated: true, note: 'Reported estimate for the Class of 2030.' },
    tests: { policy: 'flexible', sat: [1480, 1560], act: [33, 35], note: 'Test-flexible: SAT, ACT, AP or IB scores satisfy the requirement.' },
    legacy: 'strong',
    interview: 'informational',
    athletics: 'D1',
    c7: c7({ rank: VI, tests: VI, interest: NC }),
    c7Verified: false,
    majors: {},
    poolShift: 0,
    facts: [
      'Class of 2030: 779 admitted early (10.9%), 118 through QuestBridge, and 1,431 in regular decision.',
      'Of 7,140 early applicants, 18% were deferred and 70% denied.',
      'Single-Choice Early Action runs about four times the regular-decision rate.',
      'Test-flexible: AP or IB exam results can stand in for the SAT or ACT.',
    ],
    sources: [
      { label: 'Yale Common Data Set 2025–26', url: 'https://oir.yale.edu/sites/default/files/yale_cds_2025-26_md_20260616.pdf' },
      { label: 'Top Tier Admissions: Yale acceptance rate, Class of 2030', url: 'https://toptieradmissions.com/yale-acceptance-rate-class-of-2030/' },
    ],
  },
  {
    id: 'caltech',
    name: 'California Institute of Technology',
    short: 'Caltech',
    rank: 5,
    city: 'Pasadena, CA',
    admit: { rate: 0.0379, applicants: 11285, admitted: 428, cls: 2029 },
    early: { plan: 'REA', label: 'Restrictive Early Action', binding: false, restrictive: true, rate: 0.038, estimated: true, cls: null, note: 'Caltech says both rounds admit under 5% and the difference is negligible.' },
    rd: { rate: 0.037, estimated: true },
    tests: { policy: 'required', sat: [1550, 1580], act: [35, 36], note: 'CDS reports section ranges only (ERW 760–780, Math 790–800); the composite range is the sum.' },
    legacy: 'none',
    interview: 'none',
    athletics: 'D3',
    c7: c7({ tests: VI, talent: VI, interview: NC, alumni: NC, interest: NC }),
    c7Verified: false,
    majors: { humanities: 0.6, socsci: 0.7, business: 0.7, arts: 0.6 },
    poolShift: 0,
    facts: [
      'A first-year class of about 250 students; 428 admitted from 11,285 applicants (Class of 2029).',
      'Caltech states that applying early gives no meaningful advantage.',
      'Expects calculus, physics and chemistry, with alternatives accepted when a high school does not offer them.',
      'Never had legacy preference, and California law (AB 1780) now bans legacy and donor preferences at private colleges in the state.',
    ],
    sources: [
      { label: 'Caltech Common Data Set 2025–26 (collegedata.fyi)', url: 'https://www.collegedata.fyi/schools/caltech/2025-26' },
      { label: 'Oriel Admissions: Caltech acceptance rate', url: 'https://orieladmissions.com/caltech-acceptance-rate/' },
    ],
  },
  {
    id: 'stanford',
    name: 'Stanford University',
    short: 'Stanford',
    rank: 5,
    city: 'Stanford, CA',
    admit: { rate: 0.038, applicants: 60646, admitted: 2302, cls: 2029, note: 'Class of 2030 figures not released.' },
    early: { plan: 'REA', label: 'Restrictive Early Action', binding: false, restrictive: true, rate: 0.075, estimated: true, cls: null, note: 'Not published; industry estimates 7–8%.' },
    rd: { rate: 0.031, estimated: true },
    tests: { policy: 'required', sat: [1520, 1570], act: [34, 36] },
    legacy: 'none',
    interview: 'informational',
    athletics: 'D1',
    c7: c7({ rank: VI, tests: VI, talent: VI, alumni: NC, interest: NC }),
    c7Verified: false,
    majors: {},
    poolShift: 0,
    facts: [
      '60,646 applicants and 2,302 admits for the Class of 2029; 80% of admits enrolled.',
      'California AB 1780 bans legacy and donor preferences at private universities starting with the Class of 2030 cycle. About 13.6% of Stanford\'s 2023 entering class had legacy or donor ties.',
      'Restrictive Early Action: you may not apply early to another private college.',
      'Requires the SAT or ACT again.',
    ],
    sources: [
      { label: 'Stanford Common Data Set 2025–26 (collegedata.fyi)', url: 'https://www.collegedata.fyi/schools/stanford/2025-26' },
      { label: 'Stanford Daily: California bans legacy admissions preferences', url: 'https://stanforddaily.com/2024/10/01/legacy-admissions-banned-at-stanford/' },
    ],
  },
  {
    id: 'penn',
    name: 'University of Pennsylvania',
    short: 'Penn',
    rank: 7,
    city: 'Philadelphia, PA',
    admit: { rate: 0.049, applicants: 72544, admitted: 3570, cls: 2029, note: 'Class of 2030 not published; estimated near 4.1%.' },
    early: { plan: 'ED', label: 'Early Decision (binding)', binding: true, restrictive: true, rate: 0.133, applicants: 9503, admitted: 1266, cls: 2029 },
    rd: { rate: 0.037, applicants: 63041, admitted: 2304, cls: 2029 },
    tests: { policy: 'required', sat: [1510, 1570], act: [34, 35], note: 'CDS section ranges: ERW 740–770, Math 770–800.' },
    legacy: 'strong',
    interview: 'informational',
    athletics: 'D1',
    c7: c7({}),
    c7Verified: false,
    majors: { business: 0.8 },
    poolShift: 0,
    facts: [
      'Record 72,544 applicants for the Class of 2029; 4.9% admitted.',
      'Early Decision admitted 13.3% versus 3.7% in regular decision (Class of 2029). About 7,800 applied ED for the Class of 2030.',
      'You apply to one of four undergraduate schools; Wharton and the coordinated dual-degree programs (M&T, Huntsman, LSM, VIPER) are more selective than the university overall.',
      'Penn has said legacy status matters mainly for Early Decision applicants.',
    ],
    sources: [
      { label: 'Penn Common Data Set 2025–26 (collegedata.fyi)', url: 'https://www.collegedata.fyi/schools/upenn/2025-26' },
      { label: 'Daily Pennsylvanian: Class of 2030 early decision', url: 'https://www.thedp.com/article/2025/12/penn-class-of-2030-early-decision-admissions-results' },
    ],
  },
  {
    id: 'duke',
    name: 'Duke University',
    short: 'Duke',
    rank: 8,
    city: 'Durham, NC',
    admit: { rate: 0.0473, applicants: 61935, admitted: 2930, cls: 2030 },
    early: { plan: 'ED', label: 'Early Decision (binding)', binding: true, restrictive: true, rate: 0.138, applicants: 6159, admitted: 847, cls: 2030 },
    rd: { rate: 0.0373, applicants: 55776, admitted: 2083, cls: 2030 },
    tests: { policy: 'optional', sat: [1510, 1570], act: [34, 35], note: 'Test-optional for 2026–27, including for merit scholarships.' },
    legacy: 'strong',
    interview: 'informational',
    athletics: 'D1',
    c7: c7({ interest: CO, alumni: CO }),
    c7Verified: 'partial',
    majors: {},
    poolShift: 0,
    facts: [
      'Class of 2030 admit rate of 4.73% was the lowest in Duke history.',
      'Early Decision admitted 13.8% versus 3.7% in regular decision, and ED fills roughly half the class.',
      'Duke\'s Common Data Set lists both alumni relation and demonstrated interest as "considered".',
    ],
    sources: [
      { label: 'Duke Chronicle: 847 admitted early to the Class of 2030', url: 'https://dukechronicle.com/article/duke-university-early-decision-admissions-numbers-class-of-2030-20251218' },
      { label: 'Duke Common Data Set 2025–26', url: 'https://ir.provost.duke.edu/sites/default/files/CDS_PDF_2025-2026-20260622-website-published-version.pdf' },
    ],
  },
  {
    id: 'jhu',
    name: 'Johns Hopkins University',
    short: 'Johns Hopkins',
    rank: 9,
    city: 'Baltimore, MD',
    admit: { rate: 0.061, applicants: 50259, admitted: 3072, cls: 2029, note: 'Class of 2030: 2,795 admitted (553 ED I, 260 ED II, 1,982 RD); applicant total not released, estimated 5–5.8%.' },
    early: { plan: 'ED', label: 'Early Decision I & II (binding)', binding: true, restrictive: true, rate: 0.109, applicants: 7639, admitted: 835, cls: 2029 },
    rd: { rate: 0.048, estimated: true, note: '5.2% for the Class of 2029; fewer RD admits for the Class of 2030.' },
    tests: { policy: 'required', sat: [1530, 1565], act: [34, 35] },
    legacy: 'none',
    interview: 'none',
    athletics: 'D3',
    c7: c7({ alumni: NC, interest: NC, interview: NC }),
    c7Verified: false,
    majors: {},
    poolShift: 0,
    facts: [
      'Ended legacy preference in 2020, the first top-20 university to do so.',
      'Offers two binding Early Decision rounds; the combined ED rate (10.9%) is about double regular decision (5.2%).',
      'Does not offer admissions interviews.',
    ],
    sources: [
      { label: 'Johns Hopkins Common Data Set 2025–26 (collegedata.fyi)', url: 'https://www.collegedata.fyi/schools/johns-hopkins/2025-26' },
      { label: 'JHU President: To restore trust, end legacy admissions', url: 'https://president.jhu.edu/writings/2024/09/25/to-restore-trust-end-legacy-admissions' },
    ],
  },
  {
    id: 'northwestern',
    name: 'Northwestern University',
    short: 'Northwestern',
    rank: 9,
    city: 'Evanston, IL',
    admit: { rate: 0.074, applicants: 53321, admitted: null, cls: 2029, note: 'Class of 2030 held near 7% of 54,000+ applicants.' },
    early: { plan: 'ED', label: 'Early Decision (binding)', binding: true, restrictive: true, rate: 0.20, estimated: true, cls: 2029 },
    rd: { rate: 0.053, estimated: true, cls: 2029 },
    tests: { policy: 'optional', sat: [1510, 1560], act: [34, 35] },
    legacy: 'moderate',
    interview: 'informational',
    athletics: 'D1',
    c7: c7({ rigor: VI, gpa: VI, rank: IM, tests: IM, essay: IM, recs: IM, ecs: IM, talent: IM, character: IM, interest: CO }),
    c7Verified: 'partial',
    majors: {},
    poolShift: 0.1,
    facts: [
      'More than half of each recent class is admitted through Early Decision.',
      'Admitted about 20% of ED applicants versus about 5.3% in regular decision (Class of 2029).',
      'Lists demonstrated interest as "considered" in its Common Data Set.',
      'Bienen (music) and some Communication programs add auditions or portfolios.',
    ],
    sources: [
      { label: 'Northwestern Common Data Set 2025–26', url: 'https://enrollment.northwestern.edu/data/2025-2026.pdf' },
      { label: 'Daily Northwestern: Class of 2029 admission data', url: 'https://dailynorthwestern.com/2025/09/17/campus/northwesterns-preliminary-admission-data-for-class-of-2029-highlights-geographic-diversity-scholarships/' },
    ],
  },
  {
    id: 'uchicago',
    name: 'University of Chicago',
    short: 'UChicago',
    rank: 9,
    city: 'Chicago, IL',
    admit: { rate: 0.045, applicants: 45533, admitted: 2039, cls: 2029 },
    early: { plan: 'ED', label: 'Early Decision I & II (binding); non-binding EA also offered', binding: true, restrictive: true, rate: 0.20, estimated: true, cls: null, note: 'Round-level rates are not published; industry estimates 20–30% for ED versus 2–3% RD.' },
    rd: { rate: 0.025, estimated: true },
    tests: { policy: 'optional', sat: [1500, 1560], act: [34, 35] },
    legacy: 'moderate',
    interview: 'none',
    athletics: 'D3',
    c7: c7({ tests: IM, ecs: IM, talent: IM, character: IM, interview: NC }),
    c7Verified: false,
    majors: {},
    poolShift: 0,
    facts: [
      'Offers EA, ED I and ED II. UChicago does not publish round-level rates, but most of the class is believed to come from ED.',
      'Known for unusual supplemental essay prompts that reward intellectual playfulness.',
      'Test-optional; 57% of enrolled students submitted the SAT and 25% the ACT (2025–26 CDS).',
      'Has announced plans to grow the College by about 20%, to roughly 9,000 students.',
    ],
    sources: [
      { label: 'UChicago Common Data Set 2025–26', url: 'https://www.commondatasets.fyi/uchicago' },
      { label: 'Oriel Admissions: UChicago early decision', url: 'https://orieladmissions.com/uchicago-early-decision-acceptance-rate/' },
    ],
  },
  {
    id: 'columbia',
    name: 'Columbia University',
    short: 'Columbia',
    rank: 12,
    city: 'New York, NY',
    admit: { rate: 0.0423, applicants: 61031, admitted: 2581, cls: 2030 },
    early: { plan: 'ED', label: 'Early Decision (binding)', binding: true, restrictive: true, rate: 0.1396, applicants: 5868, admitted: 819, cls: 2029 },
    rd: { rate: 0.032, estimated: true, note: 'Derived from Class of 2030 totals and about 800 ED admits.' },
    tests: { policy: 'optional', sat: [1510, 1560], act: [34, 35], note: 'Test-optional for the last time in 2026–27. SAT/ACT required from August 2027 (2027–28 cycle).' },
    legacy: 'moderate',
    interview: 'none',
    athletics: 'D1',
    c7: c7({ tests: IM, rank: IM }),
    c7Verified: false,
    majors: {},
    poolShift: 0,
    facts: [
      'Largest applicant pool in its history for the Class of 2030 (61,031); 4.23% admitted.',
      'Early Decision admitted 14.0% for the Class of 2029, roughly four to five times the regular-decision rate.',
      'You apply to Columbia College or Columbia Engineering (SEAS).',
      'The last Ivy to restore required testing, effective with the 2027–28 cycle.',
    ],
    sources: [
      { label: 'Columbia first-year application requirements', url: 'https://undergrad.admissions.columbia.edu/apply/firstyear' },
      { label: 'Columbia reinstates SAT/ACT requirements for 2027–28', url: 'https://www.yahoo.com/news/us/articles/columbia-reinstates-sat-act-requirements-163100521.html' },
      { label: 'Oriel Admissions: Columbia early decision', url: 'https://orieladmissions.com/columbia-early-decision-acceptance-rate/' },
    ],
  },
  {
    id: 'dartmouth',
    name: 'Dartmouth College',
    short: 'Dartmouth',
    rank: 12,
    city: 'Hanover, NH',
    admit: { rate: 0.0585, applicants: 28863, admitted: 1687, cls: 2030 },
    early: { plan: 'ED', label: 'Early Decision (binding)', binding: true, restrictive: true, rate: 0.171, applicants: 3550, admitted: 606, cls: 2029 },
    rd: { rate: 0.044, cls: 2029 },
    tests: { policy: 'required', sat: [1440, 1550], act: [32, 35] },
    legacy: 'strong',
    interview: 'evaluative',
    athletics: 'D1',
    c7: c7({ interest: CO, alumni: CO }),
    c7Verified: 'partial',
    majors: {},
    poolShift: 0,
    facts: [
      'Smallest applicant pool in the Ivy League (28,863 for the Class of 2030).',
      'Early Decision admitted 17.1% versus 4.4% in regular decision (Class of 2029); Dartmouth declined to release Class of 2030 ED figures.',
      'Lists both alumni relation and demonstrated interest as "considered".',
      'One of the first Ivies to restore required testing.',
    ],
    sources: [
      { label: 'Valley News: Dartmouth Class of 2030 at 5.8%', url: 'https://vnews.com/2026/04/12/dartmouth-college-class-of-2030/' },
      { label: 'Dartmouth Common Data Set 2025–26', url: 'https://www.dartmouth.edu/oir/pdfs/cds_2025-26.pdf' },
    ],
  },
  {
    id: 'cmu',
    name: 'Carnegie Mellon University',
    short: 'Carnegie Mellon',
    rank: 14,
    city: 'Pittsburgh, PA',
    admit: { rate: 0.111, applicants: null, admitted: null, cls: 2029, note: 'Class of 2030 projected at 10.5–11%.' },
    early: { plan: 'ED', label: 'Early Decision (binding)', binding: true, restrictive: true, rate: 0.17, estimated: true, cls: null, note: 'Recent ED rates estimated in the mid-teens to about 20%.' },
    rd: { rate: 0.10, estimated: true },
    tests: { policy: 'required', sat: [1500, 1560], act: [34, 35] },
    legacy: 'none',
    interview: 'none',
    athletics: 'D3',
    c7: c7({ tests: VI, ecs: IM, talent: IM, character: IM, alumni: NC, interest: NC, interview: NC }),
    c7Verified: 'partial',
    majors: { cs: 0.38, engineering: 0.9, business: 0.95, socsci: 1.15, humanities: 1.15 },
    poolShift: 0.15,
    facts: [
      'You apply to a specific college. The School of Computer Science turns away about 95% of applicants, far below the university-wide rate.',
      'College of Fine Arts programs require a portfolio or audition.',
      'Ended legacy preference in July 2023.',
      'Rates demonstrated interest "not considered".',
    ],
    sources: [
      { label: 'Carnegie Mellon Common Data Set 2025–26', url: 'https://www.cmu.edu/ira/CDS/pdf/cds_2025_26/cds_2025_full_pdf.pdf' },
      { label: 'Oriel Admissions: Carnegie Mellon acceptance rate by college', url: 'https://orieladmissions.com/carnegie-mellon-acceptance-rate/' },
    ],
  },
  {
    id: 'cornell',
    name: 'Cornell University',
    short: 'Cornell',
    rank: 14,
    city: 'Ithaca, NY',
    admit: { rate: 0.0922, applicants: 65514, admitted: 6040, cls: 2030 },
    early: { plan: 'ED', label: 'Early Decision (binding)', binding: true, restrictive: true, rate: 0.1878, applicants: 10057, admitted: 1889, cls: 2029 },
    rd: { rate: 0.067, cls: 2029, note: 'Derived: (6,077 − 1,889) ÷ (72,523 − 10,057).' },
    tests: { policy: 'required', sat: [1490, 1550], act: [33, 35] },
    legacy: 'moderate',
    interview: 'none',
    athletics: 'D1',
    c7: c7({ tests: IM, talent: IM, interview: NC }),
    c7Verified: false,
    majors: { cs: 0.8, engineering: 0.8, business: 0.85 },
    poolShift: 0.15,
    facts: [
      'Highest admit rate in the Ivy League (9.22% for the Class of 2030), but you apply to one of eight undergraduate colleges with very different rates.',
      'Engineering and computer science run well below the university average; the state-contract colleges (CALS, Human Ecology, ILR) weigh New York residency.',
      'Early Decision admitted 18.8% versus about 6.7% in regular decision (Class of 2029).',
      'Requires the SAT or ACT starting with fall 2026 entry.',
    ],
    sources: [
      { label: 'Cornell Common Data Set 2025–26 (collegedata.fyi)', url: 'https://www.collegedata.fyi/schools/cornell/2025-26' },
      { label: 'Oriel Admissions: Cornell ED by college', url: 'https://orieladmissions.com/cornell-ed-by-college/' },
    ],
  },
  {
    id: 'brown',
    name: 'Brown University',
    short: 'Brown',
    rank: 16,
    city: 'Providence, RI',
    admit: { rate: 0.0535, applicants: 47937, admitted: 2564, cls: 2030 },
    early: { plan: 'ED', label: 'Early Decision (binding)', binding: true, restrictive: true, rate: 0.165, applicants: 5406, admitted: 890, cls: 2030 },
    rd: { rate: 0.0394, applicants: 42531, admitted: 1674, cls: 2030 },
    tests: { policy: 'required', sat: [1470, 1550], act: [33, 35] },
    legacy: 'moderate',
    interview: 'informational',
    athletics: 'D1',
    c7: c7({ tests: IM, ecs: IM }),
    c7Verified: false,
    majors: {},
    poolShift: 0,
    facts: [
      'Early Decision admitted 16.5% (890 of 5,406) versus 3.94% in regular decision for the Class of 2030.',
      'Open Curriculum with no distribution requirements; essays should show how you would use that freedom.',
      'A 2024 committee review kept Early Decision and legacy consideration and restored required testing.',
      'The eight-year PLME medical program and the Brown|RISD dual degree are far more selective than Brown overall.',
    ],
    sources: [
      { label: 'Brown Daily Herald: 16.5% of ED applicants admitted to the Class of 2030', url: 'https://www.browndailyherald.com/article/2025/12/as-campus-works-to-heal-brown-admits-165-of-early-decision-applicants-to-class-of-2030' },
      { label: 'Oriel Admissions: Brown acceptance rate', url: 'https://orieladmissions.com/brown-acceptance-rate/' },
    ],
  },
  {
    id: 'rice',
    name: 'Rice University',
    short: 'Rice',
    rank: 16,
    city: 'Houston, TX',
    admit: { rate: 0.077, applicants: 38603, admitted: 2984, cls: 2030 },
    early: { plan: 'ED', label: 'Early Decision I & II (binding)', binding: true, restrictive: true, rate: 0.132, cls: 2029, note: 'ED I rate; ED II admitted 6.0% in its first year, below the 7.3% RD rate.' },
    rd: { rate: 0.073, cls: 2029 },
    tests: { policy: 'optional', sat: [1510, 1560], act: [34, 36], note: 'Test-optional, but Rice recommends submitting scores if you have them.' },
    legacy: 'light',
    interview: 'informational',
    athletics: 'D1',
    c7: c7({ tests: IM, interest: CO }),
    c7Verified: 'partial',
    majors: {},
    poolShift: 0.15,
    facts: [
      'Admitted a record 447 students in ED I for the Class of 2030.',
      'ED II admitted only 6.0% in its first year, lower than regular decision, so only ED I carries a real advantage.',
      'Lists demonstrated interest as "considered".',
      'Architecture requires a portfolio and the Shepherd School of Music requires an audition.',
    ],
    sources: [
      { label: 'Rice Thresher: Rice admits 7.7% to the Class of 2030', url: 'https://ricethresher.org/article/rice-admits-7-7-of-applicants-to-the-class-of-2030-20260408' },
      { label: 'Rice Common Data Set 2025–26 (collegedata.fyi)', url: 'https://www.collegedata.fyi/schools/rice/2025-26' },
    ],
  },
  {
    id: 'vanderbilt',
    name: 'Vanderbilt University',
    short: 'Vanderbilt',
    rank: 16,
    city: 'Nashville, TN',
    admit: { rate: 0.0408, applicants: 56447, admitted: 2302, cls: 2030 },
    early: { plan: 'ED', label: 'Early Decision I & II (binding)', binding: true, restrictive: true, rate: 0.119, applicants: 7727, admitted: 920, cls: 2030 },
    rd: { rate: 0.0284, applicants: 48720, admitted: 1382, cls: 2030 },
    tests: { policy: 'optional', sat: [1510, 1560], act: [34, 35], note: 'Test-optional through fall 2027 entry; required again from the 2028–29 cycle.' },
    legacy: 'moderate',
    interview: 'none',
    athletics: 'D1',
    c7: c7({ rank: IM, tests: IM, recs: IM, interest: NC, interview: NC }),
    c7Verified: 'partial',
    majors: {},
    poolShift: 0,
    facts: [
      'Class of 2030 admit rate of 4.08% (2,302 of 56,447) was the lowest in Vanderbilt history.',
      'Early Decision admitted 11.9% (920 of 7,727) for the Class of 2030, down from 13.2% a year earlier.',
      'Regular decision admitted a record-low 2.8% (1,382 of 48,720). Because ED fills about 40% of the class, Vanderbilt\'s regular round is about as hard as Stanford\'s or Yale\'s even though its overall rate is higher.',
      'Rates demonstrated interest "not considered".',
    ],
    sources: [
      { label: 'Vanderbilt Hustler: ED rate down to 11.9% for the Class of 2030', url: 'https://vanderbilthustler.com/2026/02/17/early-decision-acceptance-rate-down-to-11-9-for-class-of-2030/' },
      { label: 'Vanderbilt Admissions: Class of 2030 regular decision by the numbers', url: 'https://admissions.vanderbilt.edu/vandybloggers/2026/04/class-of-2030-regular-decision-by-the-numbers/' },
      { label: 'Vanderbilt Admissions: Class of 2030 early decision by the numbers', url: 'https://admissions.vanderbilt.edu/vandybloggers/2026/02/class-of-2030-early-decision-by-the-numbers/' },
    ],
  },
  {
    id: 'washu',
    name: 'Washington University in St. Louis',
    short: 'WashU',
    rank: 16,
    city: 'St. Louis, MO',
    admit: { rate: 0.122, applicants: 33221, admitted: null, cls: 2030 },
    early: { plan: 'ED', label: 'Early Decision I & II (binding); new non-binding EA for 2026–27', binding: true, restrictive: true, rate: 0.253, cls: 2028, note: 'ED I and II combined, the most recent published figure.' },
    rd: { rate: 0.08, estimated: true },
    tests: { policy: 'optional', sat: [1500, 1550], act: [33, 35] },
    legacy: 'light',
    interview: 'none',
    athletics: 'D3',
    c7: c7({ interest: CO }),
    c7Verified: false,
    majors: {},
    poolShift: 0.15,
    facts: [
      'About 60% of the incoming class is admitted through the two binding ED rounds.',
      'New for 2026–27: a non-binding Early Action round and a priority deadline for scholarship programs.',
      'Reinstated demonstrated interest for 2026–27: virtual sessions, campus visits and mailing-list sign-ups count.',
      'Legacy status is described as a tiebreaker between otherwise similar applicants.',
    ],
    sources: [
      { label: 'Student Life: WashU adds Early Action for the Class of 2031 cycle', url: 'https://www.studlife.com/news/2026/04/16/washu-to-add-early-action-and-more-for-class-of-2031-undergraduate-admissions-cycle' },
      { label: 'Student Life: Class of 2030 profile', url: 'https://www.studlife.com/news/2026/09/16/class-of-2030-sees-growth-in-moderate-income-students-as-washu-prepares-admissions-changes' },
    ],
  },
  {
    id: 'berkeley',
    name: 'University of California, Berkeley',
    short: 'UC Berkeley',
    rank: 20,
    city: 'Berkeley, CA',
    admit: { rate: 0.105, applicants: null, admitted: null, cls: 2030, note: 'Fall 2026 first-year admit rate.' },
    early: null,
    rd: { rate: 0.105 },
    residency: { ca: 0.124, us: 0.10, intl: 0.054 },
    tests: { policy: 'blind', sat: null, act: null, note: 'Test-blind: SAT/ACT scores are not considered.' },
    gpa: { cappedWeighted: [4.20, 4.29], label: 'Computer science admits, UC capped weighted GPA' },
    legacy: 'none',
    interview: 'none',
    athletics: 'D1',
    c7: UC_C7,
    c7Verified: 'partial',
    majors: { cs: 0.62, engineering: 0.55, business: 0.6, socsci: 1.1, humanities: 1.2, undecided: 1.1 },
    poolShift: 0.1,
    maxChance: 0.5, // UC reads are unpredictable even for top students
    facts: [
      'Fall 2026 admit rates: 12.4% for California residents, 10.0% for other U.S. students, 5.4% for international students.',
      'Computer science admitted 7% (498 of 6,803); EECS admitted under 5%.',
      'Uses the UC application: four Personal Insight Questions (350 words each) and up to 20 activities and awards. No early round; the deadline is November 30.',
      'Readers assign a single holistic score from 1 (definite admit) to 5. Rigor, GPA and the PIQs are rated "very important".',
      'Test-blind, no legacy preference, no interviews, and letters of recommendation only if Berkeley requests them.',
    ],
    sources: [
      { label: 'Berkeleyside: Berkeley reclaims status as most selective UC (fall 2026)', url: 'https://www.berkeleyside.org/2026/07/29/uc-berkeley-admissions-fall-2026' },
      { label: 'UC Admissions: Berkeley first-year admit data', url: 'https://admission.universityofcalifornia.edu/campuses-majors/berkeley/first-year-admit-data.html' },
      { label: 'San Francisco Chronicle: UC acceptance rates and GPAs by major', url: 'https://www.sfchronicle.com/projects/2026/uc-acceptance-rate-gpa-by-major/' },
    ],
  },
  {
    id: 'ucla',
    name: 'University of California, Los Angeles',
    short: 'UCLA',
    rank: 20,
    city: 'Los Angeles, CA',
    admit: { rate: 0.108, applicants: null, admitted: null, cls: 2030, note: 'Fall 2026 first-year admit rate.' },
    early: null,
    rd: { rate: 0.108 },
    residency: { ca: 0.102, us: 0.149, intl: 0.081 },
    tests: { policy: 'blind', sat: null, act: null, note: 'Test-blind: SAT/ACT scores are not considered.' },
    gpa: { cappedWeighted: [4.25, 4.32], label: 'Computer science admits, UC capped weighted GPA' },
    legacy: 'none',
    interview: 'none',
    athletics: 'D1',
    c7: UC_C7,
    c7Verified: false,
    majors: { cs: 0.26, engineering: 0.6, natsci: 0.9, socsci: 1.05, humanities: 1.2, arts: 0.8, undecided: 1.15 },
    poolShift: 0.1,
    maxChance: 0.5,
    facts: [
      'Fall 2026 admit rates: 10.2% for California residents, 14.9% for other U.S. students, 8.1% for international students. UCLA admits out-of-state applicants at a higher rate than Californians.',
      'Computer science admitted just 3% (368 of 11,938); CS admits had capped weighted GPAs of 4.25–4.32.',
      'Uses the UC application with four Personal Insight Questions; no early round, test-blind, no legacy preference.',
      'Arts and architecture majors add portfolios or auditions.',
    ],
    sources: [
      { label: 'San Francisco Chronicle: UC acceptance rates and GPAs by major', url: 'https://www.sfchronicle.com/projects/2026/uc-acceptance-rate-gpa-by-major/' },
      { label: 'Berkeleyside: fall 2026 UC admissions', url: 'https://www.berkeleyside.org/2026/07/29/uc-berkeley-admissions-fall-2026' },
    ],
  },
  {
    id: 'notredame',
    name: 'University of Notre Dame',
    short: 'Notre Dame',
    rank: 20,
    city: 'Notre Dame, IN',
    admit: { rate: 0.09, applicants: 36102, admitted: 3249, cls: 2030 },
    early: { plan: 'REA', label: 'Restrictive Early Action', binding: false, restrictive: true, rate: 0.118, applicants: 13711, admitted: 1617, cls: 2030 },
    rd: { rate: 0.073, estimated: true, note: 'Derived: (3,249 − 1,617) ÷ (36,102 − 13,711).' },
    tests: { policy: 'optional', sat: [1460, 1540], act: [33, 35], note: 'Test-optional through 2026–27; required again from the 2027–28 cycle.' },
    legacy: 'strong',
    interview: 'none',
    athletics: 'D1',
    c7: c7({ rank: IM, tests: IM, talent: IM, interest: NC }),
    c7Verified: false,
    majors: {},
    poolShift: 0.15,
    facts: [
      'Restrictive Early Action admitted a record-low 11.8% (1,617 of 13,711) for the Class of 2030, and 19% of early applicants were deferred.',
      'Legacy carries more weight than at most peers; legacies are often reported at around a fifth to a quarter of each class.',
      'As a Catholic university, Notre Dame considers religious affiliation and commitment along with service and character.',
      'Will require the SAT or ACT again from the 2027–28 cycle.',
    ],
    sources: [
      { label: 'Notre Dame Admissions: Restrictive Early Action Class of 2030', url: 'https://admissions.nd.edu/visit-engage/stories-news/notre-dame-welcomes-the-restrictive-early-action-class-of-2030/' },
      { label: 'The Observer: early action rate sinks to 11.8%', url: 'https://www.ndsmcobserver.com/article/notre-dame-early-action-admissions-rate-sinks-to-record-low-11-8-20251222' },
    ],
  },
];

export const RESEARCH_SOURCES = [
  GENERAL_SOURCES.usnews,
  { label: 'San Francisco Chronicle: UCLA and Berkeley tied at No. 20', url: 'https://www.sfchronicle.com/college-admissions/article/uc-us-news-rankings-22443722.php' },
  { label: 'Notre Dame Observer: Notre Dame ranked No. 20 by U.S. News', url: 'https://www.ndsmcobserver.com/article/notre-dame-ranked-no-20-by-us-news-20260923' },
  { label: 'Chetty, Deming & Friedman (Opportunity Insights): Diversifying Society\'s Leaders?', url: 'https://opportunityinsights.org/wp-content/uploads/2023/07/CollegeAdmissions_Paper.pdf' },
  { label: 'Arcidiacono, Kinsler & Ransom: Legacy and Athlete Preferences at Harvard', url: 'https://public.econ.duke.edu/~psarcidi/legacyathlete.pdf' },
  { label: 'NACAC: Factors in the Admission Decision', url: 'https://www.nacacnet.org/factors-in-the-admission-decision/' },
  { label: 'Common Data Set: which top colleges consider demonstrated interest', url: 'https://gradpilot.com/news/demonstrated-interest-top-colleges-common-data-set' },
  { label: 'SAT & ACT policy tracker, 2026–27', url: 'https://www.deweysmart.com/admissions/test-policy-tracker' },
  GENERAL_SOURCES.class2030,
];

export function schoolById(id) {
  return SCHOOLS.find((s) => s.id === id);
}
